# Generated by Django 5.2.1 on 2025-05-25 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('parametros', models.JSONField(blank=True, null=True)),
                ('estado', models.CharField(default='en_progreso', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoSimulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('resultados', models.JSONField(blank=True, null=True)),
                ('resumen', models.TextField(blank=True, null=True)),
                ('simulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulacion.simulacion')),
            ],
        ),
    ]
