# Generated by Django 5.2.1 on 2025-05-25 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('naturaleza', models.CharField(choices=[('resistiva', 'Resistiva'), ('inductiva', 'Inductiva'), ('capacitiva', 'Capacitiva'), ('mixta', 'Mixta')], default='resistiva', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(default='resistiva', max_length=50)),
                ('potencia_nominal_kw', models.FloatField(default=0.0, help_text='Consumo nominal en kilovatios')),
                ('consumo_instantaneo_kw', models.FloatField(default=0.0, help_text='Consumo actual (simulado)')),
                ('voltaje_operacion', models.FloatField(default=220.0)),
                ('frecuencia', models.FloatField(default=50.0, help_text='Frecuencia de operación (Hz)')),
                ('estado', models.CharField(choices=[('desconectada', 'Desconectada'), ('conectada', 'Conectada'), ('operativa', 'Operativa'), ('sobrecarga', 'Sobrecarga')], default='desconectada', max_length=20)),
                ('controlable', models.BooleanField(default=True, help_text='Puede encenderse/apagarse por software')),
                ('prioridad', models.IntegerField(default=1, help_text='Prioridad para conexión si hay recursos limitados')),
                ('tipo_carga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cargas.tipocarga')),
            ],
        ),
    ]
