# Generated by Django 5.2.1 on 2025-05-25 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoConexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('energética', 'Energética'), ('control', 'Control'), ('información', 'Información'), ('sináptica', 'Sináptica')], default='energética', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Conexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('tipo_conexion', models.CharField(choices=[('energética', 'Energética'), ('control', 'Control'), ('información', 'Información'), ('sináptica', 'Sináptica')], default='energética', max_length=20)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('fallo', 'Fallo')], default='activa', max_length=20)),
                ('ancho_banda_kw', models.FloatField(default=0.0, help_text='Máximo flujo permitido si aplica (kW)')),
                ('metadata', models.JSONField(blank=True, help_text='Información adicional para simulación', null=True)),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conexiones.tipoconexion')),
            ],
        ),
    ]
