# Generated by Django 5.2.1 on 2025-05-25 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('tipo', models.CharField(default='indefinido', max_length=50)),
                ('potencia_nominal_kw', models.FloatField(default=0.0)),
                ('eficiencia', models.FloatField(default=1.0)),
                ('rpm_min', models.FloatField(default=0.0)),
                ('rpm_max', models.FloatField(default=0.0)),
                ('voltaje_entrada_v', models.FloatField(default=0.0, help_text='Voltaje de entrada requerido para el arranque o excitación (V)')),
                ('voltaje_entrada_requerido_v', models.FloatField(default=0.0, help_text='Voltaje mínimo necesario para este arranque')),
                ('voltaje_salida_v', models.FloatField(default=0.0)),
                ('aplicacion', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_funcional', models.CharField(choices=[('operativo', 'Operativo'), ('parado', 'Parado'), ('error', 'Error')], default='operativo', max_length=50)),
                ('puede_arrancar', models.BooleanField(default=True)),
                ('consumo_arranque_kw', models.FloatField(default=0.0, help_text='Consumo específico en arranque (kW)')),
                ('tension_minima', models.FloatField(default=0.0, help_text='Tensión mínima de operación')),
                ('firmware_version', models.CharField(blank=True, max_length=20, null=True)),
                ('arranques_disponibles', models.JSONField(blank=True, help_text='Opciones de arranque', null=True)),
                ('config_extra', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoGenerador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tecnologia', models.CharField(default='iman_fijo', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Arranque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_arranque', models.CharField(choices=[('manual', 'Manual'), ('motor_aux', 'Motor Auxiliar'), ('corriente_externa', 'Corriente Externa'), ('solar', 'Solar'), ('hidraulico', 'Hidráulico')], default='manual', max_length=30)),
                ('costo_arranque_kw', models.FloatField(default=0.0)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('generador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arranques', to='generadores.generador')),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('capacidad_kw', models.FloatField(default=0.0)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('operativo', 'Operativo'), ('mantenimiento', 'Mantenimiento'), ('fallo', 'Fallo')], default='operativo', max_length=20)),
                ('generadores', models.ManyToManyField(blank=True, related_name='racks', to='generadores.generador')),
            ],
        ),
        migrations.AddField(
            model_name='generador',
            name='tipo_generador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generadores.tipogenerador'),
        ),
    ]
