# Generated by Django 5.2.1 on 2025-05-25 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tecnologia', models.CharField(default='batería', help_text='Tipo de tecnología: batería, volante de inercia, supercondensador, etc.', max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReservaEnergetica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('tipo', models.CharField(default='batería', max_length=50)),
                ('capacidad_actual_kw', models.FloatField(default=0.0, help_text='Cantidad actual de energía almacenada (kW)')),
                ('capacidad_max_kw', models.FloatField(default=0.0, help_text='Capacidad máxima de almacenamiento (kW)')),
                ('ciclos_vida', models.IntegerField(default=1000)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('descargando', 'Descargando'), ('cargando', 'Cargando'), ('agotada', 'Agotada')], default='disponible', max_length=20)),
                ('fecha_instalacion', models.DateField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('tipo_reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacenamiento.tiporeserva')),
            ],
        ),
    ]
