# Generated by Django 5.2.1 on 2025-05-25 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('tipo', models.CharField(default='', max_length=50)),
                ('es_secuenciador', models.BooleanField(default=False)),
                ('potencia', models.FloatField(default=0.0)),
                ('estado', models.CharField(default='operativo', max_length=50)),
                ('parametros_operacion', models.JSONField(blank=True, null=True)),
                ('celula_asociada', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoOrganulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('parametros_defecto', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DispositivoControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('tipo', models.CharField(default='control', max_length=50)),
                ('parametros', models.JSONField(blank=True, null=True)),
                ('estado', models.CharField(default='operativo', max_length=50)),
                ('organulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_control', to='organulos.organulo')),
            ],
        ),
        migrations.CreateModel(
            name='Secuenciador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('listo', 'Listo'), ('operando', 'Operando'), ('error', 'Error')], default='listo', max_length=20)),
                ('ultima_activacion', models.DateTimeField(blank=True, null=True)),
                ('parametros', models.JSONField(blank=True, null=True)),
                ('organulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secuenciadores', to='organulos.organulo')),
            ],
        ),
    ]
