# Generated by Django 5.2.1 on 2025-05-25 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('tipo', models.CharField(default='desconocido', max_length=50)),
                ('umbral_alerta', models.FloatField(default=0.0, help_text='Valor de umbral para disparar alerta')),
                ('intervalo_medicion', models.IntegerField(default=60, help_text='Intervalo en segundos entre mediciones')),
                ('estado', models.CharField(choices=[('ok', 'OK'), ('alerta', 'Alerta'), ('error', 'Error')], default='ok', max_length=20)),
                ('ultima_medicion', models.FloatField(default=0.0)),
                ('unidad', models.CharField(default='kW', max_length=20)),
                ('metadatos', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(default='eléctrico', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='multímetro', max_length=50)),
                ('precision', models.FloatField(default=0.01)),
                ('intervalo_lectura', models.IntegerField(default=60)),
                ('valor_actual', models.FloatField(default=0.0)),
                ('unidad', models.CharField(default='kW', max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('apagado', 'Apagado'), ('error', 'Error')], default='activo', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('asociado_a_sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensores.sensor')),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='tipo_sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensores.tiposensor'),
        ),
    ]
