# Generated by Django 5.2.1 on 2025-05-25 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTejido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nivel_estructura', models.CharField(choices=[('básico', 'Básico'), ('intermedio', 'Intermedio'), ('complejo', 'Complejo')], default='básico', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tejido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('celulas', models.JSONField(blank=True, help_text='IDs de células que forman el tejido', null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('en_formación', 'En formación'), ('dañado', 'Dañado'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('energia_total_kw', models.FloatField(default=0.0)),
                ('productividad', models.FloatField(default=1.0, help_text='Factor multiplicador de producción o eficiencia')),
                ('metadata', models.JSONField(blank=True, help_text='Datos adicionales: ubicación, historia, etc.', null=True)),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tejidos.tipotejido')),
            ],
        ),
    ]
