# Generated by Django 5.2.1 on 2025-05-25 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('tipo', models.CharField(default='', max_length=50)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_activacion', models.DateTimeField(auto_now_add=True)),
                ('estado_funcional', models.CharField(choices=[('activa', 'Activa'), ('latente', 'Latente'), ('inactiva', 'Inactiva')], default='activa', max_length=50)),
                ('energia_actual', models.FloatField(default=0.0)),
                ('energia_maxima', models.FloatField(default=0.0)),
                ('nivel_evolucion', models.IntegerField(default=1)),
                ('historial', models.JSONField(blank=True, null=True)),
                ('puede_multiplicar', models.BooleanField(default=False)),
                ('enlaces', models.JSONField(blank=True, help_text='IDs de conexiones funcionales', null=True)),
                ('posibles_evoluciones', models.JSONField(blank=True, null=True)),
                ('productiva', models.BooleanField(default=True)),
                ('consumo_kw', models.FloatField(default=0.0)),
                ('produccion_kw', models.FloatField(default=0.0)),
                ('generadores', models.JSONField(blank=True, null=True)),
                ('organulos', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCelula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=50)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('celula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='celulas.celula')),
            ],
        ),
        migrations.CreateModel(
            name='EvolucionCelula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_evolucion', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('celula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evoluciones', to='celulas.celula')),
                ('nueva_celula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origen_evolucion', to='celulas.celula')),
            ],
        ),
        migrations.CreateModel(
            name='UbicacionCelula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('z', models.FloatField(default=0.0)),
                ('celula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion_detallada', to='celulas.celula')),
            ],
        ),
    ]
