# Generated by Django 5.2.1 on 2025-05-25 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tecnologia', models.CharField(default='DC', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('tipo', models.CharField(default='indefinido', max_length=50)),
                ('potencia_nominal_kw', models.FloatField(default=0.0)),
                ('rpm_nominal', models.FloatField(default=0.0)),
                ('corriente_nominal', models.FloatField(default=0.0)),
                ('voltaje_operacion_v', models.FloatField(default=0.0)),
                ('eficiencia', models.FloatField(default=0.9)),
                ('consumo_arranque_kw', models.FloatField(default=0.0)),
                ('ciclos_vida', models.IntegerField(default=10000)),
                ('estado', models.CharField(choices=[('operativo', 'Operativo'), ('mantenimiento', 'Mantenimiento'), ('fallo', 'Fallo')], default='operativo', max_length=20)),
                ('firmware_version', models.CharField(blank=True, max_length=20, null=True)),
                ('config_extra', models.JSONField(blank=True, null=True)),
                ('tipo_motor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='motores.tipomotor')),
            ],
        ),
    ]
